const ADD_COMPANY_PORTFOLIO = 'ADD_COMPANY_PORTFOLIO';
const ADD_COMPANY_WATCHLIST = 'ADD_COMPANY_WATCHLIST';
const REMOVE_COMPANY_WATCHLIST = 'REMOVE_COMPANY_WATCHLIST';
const SET_WATCHLIST_FROM_DB = 'SET_WATCHLIST_FROM_DB';
const SET_PORTFOLIO_FROM_DB = 'SET_PORTFOLIO_FROM_DB';
const GET_RESEARCH_COMPANY = 'GET_RESEARCH_COMPANY';
const SET_RESEARCH_COMPANY = 'SET_RESEARCH_COMPANY';
const SET_MARKET_MOVERS = 'SET_MARKET_MOVERS';
const SET_USER = 'SET_USER';


export default {
    ADD_COMPANY_PORTFOLIO,
    ADD_COMPANY_WATCHLIST,
    REMOVE_COMPANY_WATCHLIST,
    SET_WATCHLIST_FROM_DB,
    SET_PORTFOLIO_FROM_DB,
    SET_RESEARCH_COMPANY,
    GET_RESEARCH_COMPANY,
    SET_MARKET_MOVERS,
    SET_USER
}